name: gravomg
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.9
  - setuptools=65.6.3
  - wheel=0.37.1
  - pip:
      - libigl==2.4.1
      - numpy==1.24.1
      - pandas==2.0.3
      - plyfile==0.7.4
      - polyscope==1.3.1
      - pyamg==5.0.1
      - robust-laplacian==0.2.4
      - scipy==1.10.0
      - tabulate==0.9.0